/** USERS */
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_ACTIVE_USER = 'UPDATE_ACTIVE_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN';

/** GROUPS */
export const UPDATE_GROUP_LIST = 'UPDATE_GROUP_LIST';
export const UPDATE_ACTIVE_USER_GROUPS = 'UPDATE_ACTIVE_USER_GROUPS';
export const UPDATE_ACTIVE_GROUP = 'UPDATE_ACTIVE_GROUP';
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';
export const UPDATE_GROUP_DETAILS = 'UPDATE_GROUP_DETAILS';

/** PAGES */
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const TURN_OFF_MESSAGE = 'TURN_OFF_MESSAGE';
export const UPDATE_LOADER_STATUS = 'UPDATE_LOADER_STATUS';
export const UPDATE_ACTIVE_USER_IN_USERS_PAGE =
  'UPDATE_ACTIVE_USER_IN_USERS_PAGE';
export const UPDATE_ACTIVE_RIGHT_COL_USERS_PAGE =
  'UPDATE_ACTIVE_RIGHT_COL_USERS_PAGE';
export const UPDATE_SHOW_STATUS_CREATE_GROUP_FORM =
  'UPDATE_SHOW_STATUS_CREATE_GROUP_FORM';
