# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Symfony\Component\HttpFoundation\JsonResponse: ~

    App\Core\Search\Criteria: ~
    App\Entity\AdminUser: ~

    App\Entity\User: ~
    App\Service\User\CreateUserServiceProvider: ~
    App\Entity\User\ResourceModel\User: ~
    App\Entity\User\Collection\UserCollectionSearchResult: ~
    App\Service\User\CollectUsersServiceProvider: ~
    App\Repository\UserRepository: ~

    App\Entity\Group: ~
    App\Service\Group\CreateGroupServiceProvider: ~
    App\Entity\Group\ResourceModel\Group: ~
    App\Entity\Group\Collection\GroupCollectionSearchResult: ~
    App\Service\Group\CollectGroupsServiceProvider: ~
    App\Repository\GroupRepository: ~

    App\Entity\UserGroupRelation: ~
    App\Service\User\AssignGroupServiceProvider: ~
    App\Service\User\UnAssignGroupServiceProvider: ~
    App\Entity\User\ResourceModel\UserGroupRelation: ~
    App\Repository\UserManagement: ~


    # Interface mapping goes here...
    App\Api\Search\CriteriaInterface: '@App\Core\Search\Criteria'
    Symfony\Component\Security\Core\User\UserInterface: '@App\Entity\AdminUser'

    App\Api\User\Data\UserInterface: '@App\Entity\User'
    App\Api\User\Data\SearchResultInterface: '@App\Entity\User\Collection\UserCollectionSearchResult'
    App\Api\User\UserRepositoryInterface: '@App\Repository\UserRepository'

    App\Api\Group\Data\GroupInterface: '@App\Entity\Group'
    App\Api\Group\Data\SearchResultInterface: '@App\Entity\Group\Collection\GroupCollectionSearchResult'
    App\Api\Group\GroupRepositoryInterface: '@App\Repository\GroupRepository'

    App\Api\User\UserManagementInterface: '@App\Repository\UserManagement'
    App\Api\User\Data\UserGroupRelationInterface: '@App\Entity\UserGroupRelation'

